### ISSUE TITLE
FreezeFrog should also mock datetime.datetime.now

### ISSUE THREAD

**Issue by lucasvo** [closeio/freezefrog#1]
FreezeFrog should raise an exception when datetime.datetime.now() is used without a TZ instead of not mocking it at all.

**Comment by lucasvo** [comment]
Unfortunately we have libraries that use dateime.now() and therefore unless we mock datetime.now() we won't be able to use those. As nice as it is, unless we start monkey patching libraries or go on a crusade to eradicate datetime.now() from the world, we need to be able to patch datetime.now()

**Comment by thomasst** [comment]
This was done in https://github.com/closeio/freezefrog/commit/2e653ab2c363208ddb7fc2958cc4bc81d7e72952

**Comment by thomasst** [comment]
(For issues with it, see https://github.com/closeio/freezefrog/issues/10)
